# Generated by Django 4.0.1 on 2022-01-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='imgi',
            field=models.ImageField(default=' ', upload_to='img'),
            preserve_default=False,
        ),
    ]
