# Generated by Django 4.0.1 on 2022-01-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_imagem_imgi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens_nossas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgi', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='imgi',
        ),
    ]
